# General feature configuration
features:
  # The chest feature randomly spawns chests in certain areas.
  # It contains custom weapons featured in the weapon feature
  chests:
    # Wether or not the chests feature should be enabled.
    enabled: true
    # Spawning details to define how much and where the chests should spawn
    spawning:
      # Spawn chance, a number from 1-1000 to define the chance per chunk to spawn a chest.
      spawn-chance: 50
      # Define how high the chests may spawn
      minY: 20
      maxY: 30